name: Build CSharpSourceObfuscator

on:
  push:
    branches:
      - main # 如果您的默认分支是 master，请改为 master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # CSharpSourceObfuscator 项目基于 .NET 6.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish RoslynObfuscator
      run: dotnet publish RoslynObfuscator/RoslynObfuscator.csproj --configuration Release --no-build --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CSharpSourceObfuscator-exe
        path: ./publish/


